//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gip.vb.mobile.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gip.vb.mobile.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_Label {
            get {
                return ResourceManager.GetString("About_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string ACMethodParamPivot_Header {
            get {
                return ResourceManager.GetString("ACMethodParamPivot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual values.
        /// </summary>
        internal static string ACMethodResultPivot_Header {
            get {
                return ResourceManager.GetString("ACMethodResultPivot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation/deactivation is not successful..
        /// </summary>
        internal static string ActIsNotSuccessful_Text {
            get {
                return ResourceManager.GetString("ActIsNotSuccessful_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active quant:.
        /// </summary>
        internal static string ActiveFC_Text {
            get {
                return ResourceManager.GetString("ActiveFC_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation is successful..
        /// </summary>
        internal static string ActSuccessful_Text {
            get {
                return ResourceManager.GetString("ActSuccessful_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButton_Label {
            get {
                return ResourceManager.GetString("AddButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item with scanned barcode is already in the list. Do you still want add item?.
        /// </summary>
        internal static string AlreadAddedItem_Text {
            get {
                return ResourceManager.GetString("AlreadAddedItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned printer:.
        /// </summary>
        internal static string AssignedPrinter_Label {
            get {
                return ResourceManager.GetString("AssignedPrinter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        internal static string AvailabilityFCPivotItem {
            get {
                return ResourceManager.GetString("AvailabilityFCPivotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Available_Text {
            get {
                return ResourceManager.GetString("Available_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan or Enter Barcode.
        /// </summary>
        internal static string BarcodeScan_Text {
            get {
                return ResourceManager.GetString("BarcodeScan_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan or Enter the process function Barcode .
        /// </summary>
        internal static string BarcodeScanProdOrder_Text {
            get {
                return ResourceManager.GetString("BarcodeScanProdOrder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode sequence already have scanned code!.
        /// </summary>
        internal static string BarcodeSequenceAlreadyHaveCode_Text {
            get {
                return ResourceManager.GetString("BarcodeSequenceAlreadyHaveCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings.
        /// </summary>
        internal static string BFI_Bookings_Header {
            get {
                return ResourceManager.GetString("BFI_Bookings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Inventory Positions.
        /// </summary>
        internal static string BFI_InventoryPositionsFilter_Header {
            get {
                return ResourceManager.GetString("BFI_InventoryPositionsFilter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position edit.
        /// </summary>
        internal static string BFI_PositionEdit_Header {
            get {
                return ResourceManager.GetString("BFI_PositionEdit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Line Overview.
        /// </summary>
        internal static string BFI_PositionOverview_Header {
            get {
                return ResourceManager.GetString("BFI_PositionOverview_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Inventories.
        /// </summary>
        internal static string BFI_SearchInventory_Header {
            get {
                return ResourceManager.GetString("BFI_SearchInventory_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following quants are not registered or have problem:.
        /// </summary>
        internal static string BookAndFinishPickingError_Text {
            get {
                return ResourceManager.GetString("BookAndFinishPickingError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting journal.
        /// </summary>
        internal static string BookingHistory_Header {
            get {
                return ResourceManager.GetString("BookingHistory_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting quantity.
        /// </summary>
        internal static string BookingQuantity_Text {
            get {
                return ResourceManager.GetString("BookingQuantity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add quant to stock.
        /// </summary>
        internal static string Btn_AddQuantToStock {
            get {
                return ResourceManager.GetString("Btn_AddQuantToStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit again.
        /// </summary>
        internal static string Btn_EditQuantAgain {
            get {
                return ResourceManager.GetString("Btn_EditQuantAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find material in the warehouse.
        /// </summary>
        internal static string Btn_FindMaterialInWarehouse {
            get {
                return ResourceManager.GetString("Btn_FindMaterialInWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show grouped by materail.
        /// </summary>
        internal static string Btn_GroupByMaterial {
            get {
                return ResourceManager.GetString("Btn_GroupByMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show orders.
        /// </summary>
        internal static string Btn_ShowPickingOrders {
            get {
                return ResourceManager.GetString("Btn_ShowPickingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string BtnActivate_Text {
            get {
                return ResourceManager.GetString("BtnActivate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string BtnApply_Text {
            get {
                return ResourceManager.GetString("BtnApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign printer.
        /// </summary>
        internal static string BtnAssignPrinter_Text {
            get {
                return ResourceManager.GetString("BtnAssignPrinter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Quant.
        /// </summary>
        internal static string BtnBlockQuant_Text {
            get {
                return ResourceManager.GetString("BtnBlockQuant_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post and finish.
        /// </summary>
        internal static string BtnBookAndFinish_Text {
            get {
                return ResourceManager.GetString("BtnBookAndFinish_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string BtnClose_Text {
            get {
                return ResourceManager.GetString("BtnClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create quant.
        /// </summary>
        internal static string BtnCreateQuant {
            get {
                return ResourceManager.GetString("BtnCreateQuant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string BtnDeactivate_Text {
            get {
                return ResourceManager.GetString("BtnDeactivate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string BtnDoBooking_Text {
            get {
                return ResourceManager.GetString("BtnDoBooking_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quant not available.
        /// </summary>
        internal static string BtnDoZeroStock_Text {
            get {
                return ResourceManager.GetString("BtnDoZeroStock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter production data.
        /// </summary>
        internal static string BtnEnterACMParams_Text {
            get {
                return ResourceManager.GetString("BtnEnterACMParams_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish order.
        /// </summary>
        internal static string BtnFinishOrder {
            get {
                return ResourceManager.GetString("BtnFinishOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less.
        /// </summary>
        internal static string BtnLes_Text {
            get {
                return ResourceManager.GetString("BtnLes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to warehouse overview.
        /// </summary>
        internal static string BtnLocationOverview_Text {
            get {
                return ResourceManager.GetString("BtnLocationOverview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string BtnMore_Text {
            get {
                return ResourceManager.GetString("BtnMore_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupy machine with order.
        /// </summary>
        internal static string BtnOccupyMachine_Text {
            get {
                return ResourceManager.GetString("BtnOccupyMachine_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release machine.
        /// </summary>
        internal static string BtnReleaseMachine_Text {
            get {
                return ResourceManager.GetString("BtnReleaseMachine_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Quant.
        /// </summary>
        internal static string BtnReleaseQuant_Text {
            get {
                return ResourceManager.GetString("BtnReleaseQuant_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relocate Quant.
        /// </summary>
        internal static string BtnRelocate_Text {
            get {
                return ResourceManager.GetString("BtnRelocate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string BtnSearch_Text {
            get {
                return ResourceManager.GetString("BtnSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split quant.
        /// </summary>
        internal static string BtnSplitQuant_Text {
            get {
                return ResourceManager.GetString("BtnSplitQuant_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string BtnStart_Text {
            get {
                return ResourceManager.GetString("BtnStart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take quantity negative.
        /// </summary>
        internal static string BtnTakeQuantityNegative {
            get {
                return ResourceManager.GetString("BtnTakeQuantityNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take quantity positive.
        /// </summary>
        internal static string BtnTakeQuantityPositive {
            get {
                return ResourceManager.GetString("BtnTakeQuantityPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quant available.
        /// </summary>
        internal static string BtnUnDoZeroStock_Text {
            get {
                return ResourceManager.GetString("BtnUnDoZeroStock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string BtnUpdate_Text {
            get {
                return ResourceManager.GetString("BtnUpdate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the posting quantity:.
        /// </summary>
        internal static string ChangePostingQ_Text {
            get {
                return ResourceManager.GetString("ChangePostingQ_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose group:.
        /// </summary>
        internal static string ChooseGroup_Text {
            get {
                return ResourceManager.GetString("ChooseGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment_Text {
            get {
                return ResourceManager.GetString("Comment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction.
        /// </summary>
        internal static string Correction_Text {
            get {
                return ResourceManager.GetString("Correction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string DateFrom_Text {
            get {
                return ResourceManager.GetString("DateFrom_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string DateTo_Text {
            get {
                return ResourceManager.GetString("DateTo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivation is successful..
        /// </summary>
        internal static string DeactSuccessful_Text {
            get {
                return ResourceManager.GetString("DeactSuccessful_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanned item has different expiration date that items in the list. It&apos;s only allowed sum items with same expiration date..
        /// </summary>
        internal static string DifferentExpDateInList_Text {
            get {
                return ResourceManager.GetString("DifferentExpDateInList_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanned item has different LOT that items in the list. It&apos;s only allowed sum items with same LOT number..
        /// </summary>
        internal static string DifferentLotInList_Text {
            get {
                return ResourceManager.GetString("DifferentLotInList_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order picking.
        /// </summary>
        internal static string DoPickingPivot_Header {
            get {
                return ResourceManager.GetString("DoPickingPivot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode entity is empty! Please scan first..
        /// </summary>
        internal static string EmptyBarcodeEntity_Text {
            get {
                return ResourceManager.GetString("EmptyBarcodeEntity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap again to exit iPlus Mobile.
        /// </summary>
        internal static string ExitHint_Text {
            get {
                return ResourceManager.GetString("ExitHint_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore storage.
        /// </summary>
        internal static string ExploreStorage_Text {
            get {
                return ResourceManager.GetString("ExploreStorage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FacilityName_Text {
            get {
                return ResourceManager.GetString("FacilityName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string FacilityNo_Text {
            get {
                return ResourceManager.GetString("FacilityNo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The facility is not selected. Please, select or scan facility..
        /// </summary>
        internal static string FacilityNotSelected_Text {
            get {
                return ResourceManager.GetString("FacilityNotSelected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Bin.
        /// </summary>
        internal static string FacilityPivot_Header {
            get {
                return ResourceManager.GetString("FacilityPivot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Storage Bin No. or Name.
        /// </summary>
        internal static string FacilitySearch_Text {
            get {
                return ResourceManager.GetString("FacilitySearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search only in list (filter list).
        /// </summary>
        internal static string FacilitySelSearchOnlyList_text {
            get {
                return ResourceManager.GetString("FacilitySelSearchOnlyList_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quant matches the inventory line..
        /// </summary>
        internal static string FC_Match_Text {
            get {
                return ResourceManager.GetString("FC_Match_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quant not exist!.
        /// </summary>
        internal static string FC_NotExist_Text {
            get {
                return ResourceManager.GetString("FC_NotExist_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaned quant (ID: {0}) not match selected (ID: {1})!.
        /// </summary>
        internal static string FC_NotMatch_Text {
            get {
                return ResourceManager.GetString("FC_NotMatch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quant was already counted..
        /// </summary>
        internal static string FC_QuantAlreadyFinished {
            get {
                return ResourceManager.GetString("FC_QuantAlreadyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quant is available on different Faciltiy: {0}!.
        /// </summary>
        internal static string FC_QuantOnDifferentFaciltiy {
            get {
                return ResourceManager.GetString("FC_QuantOnDifferentFaciltiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quant is not available! Get the quant back into stock if there is physical inventory..
        /// </summary>
        internal static string FC_QuantRestoreNotAvailable {
            get {
                return ResourceManager.GetString("FC_QuantRestoreNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter_Text {
            get {
                return ResourceManager.GetString("Filter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From storage location.
        /// </summary>
        internal static string FromStorageLocation_Text {
            get {
                return ResourceManager.GetString("FromStorageLocation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Go and count.
        /// </summary>
        internal static string GoAndCount_Text {
            get {
                return ResourceManager.GetString("GoAndCount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input_Text {
            get {
                return ResourceManager.GetString("Input_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input materials.
        /// </summary>
        internal static string InputMaterials_Header {
            get {
                return ResourceManager.GetString("InputMaterials_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Product.
        /// </summary>
        internal static string Intermediate_Text {
            get {
                return ResourceManager.GetString("Intermediate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory - Edit line.
        /// </summary>
        internal static string Inv_EditLine {
            get {
                return ResourceManager.GetString("Inv_EditLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory - Search Line.
        /// </summary>
        internal static string Inv_EditLineS {
            get {
                return ResourceManager.GetString("Inv_EditLineS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory - open positions.
        /// </summary>
        internal static string Inv_OpenPositions {
            get {
                return ResourceManager.GetString("Inv_OpenPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory - select storage location / bin.
        /// </summary>
        internal static string Inv_SelectStorage {
            get {
                return ResourceManager.GetString("Inv_SelectStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        internal static string InventoryPosNotAvailable_Text {
            get {
                return ResourceManager.GetString("InventoryPosNotAvailable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory position state.
        /// </summary>
        internal static string InventoryPosState_Text {
            get {
                return ResourceManager.GetString("InventoryPosState_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Quantity.
        /// </summary>
        internal static string InventoryPosZeroQuantity_Text {
            get {
                return ResourceManager.GetString("InventoryPosZeroQuantity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory state.
        /// </summary>
        internal static string InventoryState_Text {
            get {
                return ResourceManager.GetString("InventoryState_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlus Url.
        /// </summary>
        internal static string IPlusBackendUrl_Text {
            get {
                return ResourceManager.GetString("IPlusBackendUrl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        internal static string LightTheme_Text {
            get {
                return ResourceManager.GetString("LightTheme_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Location.
        /// </summary>
        internal static string LocationPivot_Header {
            get {
                return ResourceManager.GetString("LocationPivot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Storage Location No. or Name .
        /// </summary>
        internal static string LocationSearch_Text {
            get {
                return ResourceManager.GetString("LocationSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Storage Location.
        /// </summary>
        internal static string LocationSelect_Text {
            get {
                return ResourceManager.GetString("LocationSelect_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coudn&apos;t connect to iPlus-Service. Please check if iPlus-Service is running or you network and firewal settings..
        /// </summary>
        internal static string LoginError_Text {
            get {
                return ResourceManager.GetString("LoginError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed!.
        /// </summary>
        internal static string LoginFail_Text {
            get {
                return ResourceManager.GetString("LoginFail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Login-Request is still active. Please wait for response!.
        /// </summary>
        internal static string LoginRequestActive_Text {
            get {
                return ResourceManager.GetString("LoginRequestActive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        internal static string LotPivot_Header {
            get {
                return ResourceManager.GetString("LotPivot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Lot No..
        /// </summary>
        internal static string LotSearch_Text {
            get {
                return ResourceManager.GetString("LotSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The material is not selected. Please, select material..
        /// </summary>
        internal static string MaterialNotSelected_Text {
            get {
                return ResourceManager.GetString("MaterialNotSelected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string MaterialPivot_Header {
            get {
                return ResourceManager.GetString("MaterialPivot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Material No. or Name.
        /// </summary>
        internal static string MaterialSearch_Text {
            get {
                return ResourceManager.GetString("MaterialSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The neto weight cannot be parsed..
        /// </summary>
        internal static string NetWeightParseError_Text {
            get {
                return ResourceManager.GetString("NetWeightParseError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New quant.
        /// </summary>
        internal static string NewQuant_Text {
            get {
                return ResourceManager.GetString("NewQuant_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Stock.
        /// </summary>
        internal static string NewStockQuantity_Text {
            get {
                return ResourceManager.GetString("NewStockQuantity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is finished!.
        /// </summary>
        internal static string OrderFinished_Text {
            get {
                return ResourceManager.GetString("OrderFinished_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output_Text {
            get {
                return ResourceManager.GetString("Output_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill of material name.
        /// </summary>
        internal static string PartslistName_Label {
            get {
                return ResourceManager.GetString("PartslistName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password_Text {
            get {
                return ResourceManager.GetString("Password_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The posting was successful. Please print labels now and stick them on the material. How many labels do you want to print?.
        /// </summary>
        internal static string PickingBookSuccAndPrint_Question {
            get {
                return ResourceManager.GetString("PickingBookSuccAndPrint_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouped by material.
        /// </summary>
        internal static string PickingByMaterial_Header {
            get {
                return ResourceManager.GetString("PickingByMaterial_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order picking grouped by material is only recommended with the picking type filter selected!.
        /// </summary>
        internal static string PickingByMaterialWarning_Text {
            get {
                return ResourceManager.GetString("PickingByMaterialWarning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking orders.
        /// </summary>
        internal static string PickingOrders_Text {
            get {
                return ResourceManager.GetString("PickingOrders_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string PickingPosPivot_Header {
            get {
                return ResourceManager.GetString("PickingPosPivot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok. Post now or scan the storage place where you want to relocate..
        /// </summary>
        internal static string PickingRelocationScanFacility_Text {
            get {
                return ResourceManager.GetString("PickingRelocationScanFacility_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok. Scan now quant that you want relocate..
        /// </summary>
        internal static string PickingRelocationScanFacilityCharge_Text {
            get {
                return ResourceManager.GetString("PickingRelocationScanFacilityCharge_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong scan. Please scan a quant!.
        /// </summary>
        internal static string PickingWrongBarcodeEntityQ_Text {
            get {
                return ResourceManager.GetString("PickingWrongBarcodeEntityQ_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong scan. Please scan a quant or storage place!.
        /// </summary>
        internal static string PickingWrongBarcodeEntityQF_Text {
            get {
                return ResourceManager.GetString("PickingWrongBarcodeEntityQF_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material of the quant does not match the material of the picking position!.
        /// </summary>
        internal static string PickingWrongMaterial_Text {
            get {
                return ResourceManager.GetString("PickingWrongMaterial_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position detail.
        /// </summary>
        internal static string PositionDetail_Header {
            get {
                return ResourceManager.GetString("PositionDetail_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string PosState_Text {
            get {
                return ResourceManager.GetString("PosState_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting.
        /// </summary>
        internal static string PostingFCPivot_Header {
            get {
                return ResourceManager.GetString("PostingFCPivot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The posting quantity is insufficient. Are sure that you want to continue?.
        /// </summary>
        internal static string PostingQInsufficient_Question {
            get {
                return ResourceManager.GetString("PostingQInsufficient_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting Q:.
        /// </summary>
        internal static string PostingQuantity_Text {
            get {
                return ResourceManager.GetString("PostingQuantity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The posting was successful..
        /// </summary>
        internal static string PostingSuccesful_Text {
            get {
                return ResourceManager.GetString("PostingSuccesful_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many label copies do you want to print?.
        /// </summary>
        internal static string PrintCopies_Question {
            get {
                return ResourceManager.GetString("PrintCopies_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stock movement line (posting line) coudn&apos;t be found for printing..
        /// </summary>
        internal static string PrintFBCMissing_Text {
            get {
                return ResourceManager.GetString("PrintFBCMissing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quant coudn&apos;t be found for printing..
        /// </summary>
        internal static string PrintQuantMissing_Text {
            get {
                return ResourceManager.GetString("PrintQuantMissing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting.
        /// </summary>
        internal static string ProdOrderInOutBooking_Header {
            get {
                return ResourceManager.GetString("ProdOrderInOutBooking_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string ProdOrderInOutBookingHistory_Header {
            get {
                return ResourceManager.GetString("ProdOrderInOutBookingHistory_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string ProdOrderInOutInfo_Header {
            get {
                return ResourceManager.GetString("ProdOrderInOutInfo_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quant activation/deactivation.
        /// </summary>
        internal static string QuantActivationDeactivation_Text {
            get {
                return ResourceManager.GetString("QuantActivationDeactivation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quant diff. Q:.
        /// </summary>
        internal static string QuantDiffQuantity_Text {
            get {
                return ResourceManager.GetString("QuantDiffQuantity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quant is not available. Please check are you scan correct quant..
        /// </summary>
        internal static string QuantIsNotAvailableCheck {
            get {
                return ResourceManager.GetString("QuantIsNotAvailableCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quants.
        /// </summary>
        internal static string QuantPivot_Header {
            get {
                return ResourceManager.GetString("QuantPivot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quant relocation.
        /// </summary>
        internal static string QuantRelocation_Text {
            get {
                return ResourceManager.GetString("QuantRelocation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quant split.
        /// </summary>
        internal static string QuantSplit_Text {
            get {
                return ResourceManager.GetString("QuantSplit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the split number:.
        /// </summary>
        internal static string QuantSplitNo_Text {
            get {
                return ResourceManager.GetString("QuantSplitNo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to picking workplace:.
        /// </summary>
        internal static string RegisterToWorkplace_Text {
            get {
                return ResourceManager.GetString("RegisterToWorkplace_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want RELEASE machine? If you are, then enter number 1 and confirm to release machine..
        /// </summary>
        internal static string ReleaseMachine_Question {
            get {
                return ResourceManager.GetString("ReleaseMachine_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting was successful but data for relocated quant couldn&apos;t be retrieved! Please go to warehouse overview then scan the storage place, select the relocated quant and print label manually!.
        /// </summary>
        internal static string RelocatedQuantDataMissing_Text {
            get {
                return ResourceManager.GetString("RelocatedQuantDataMissing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relocation.
        /// </summary>
        internal static string Relocation_Text {
            get {
                return ResourceManager.GetString("Relocation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode/RFID.
        /// </summary>
        internal static string ScanBarcodePivot_Header {
            get {
                return ResourceManager.GetString("ScanBarcodePivot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A storage place must be scanned!.
        /// </summary>
        internal static string ScanFActivate_Text {
            get {
                return ResourceManager.GetString("ScanFActivate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan a quant for activation or deactivation..
        /// </summary>
        internal static string ScanFCActivate_Text {
            get {
                return ResourceManager.GetString("ScanFCActivate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quant must be scanned!.
        /// </summary>
        internal static string ScanFCToActivate_Text {
            get {
                return ResourceManager.GetString("ScanFCToActivate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned quant is not currently required!.
        /// </summary>
        internal static string ScannedFCIsNotReq_Text {
            get {
                return ResourceManager.GetString("ScannedFCIsNotReq_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan a quant for activation or deactivation..
        /// </summary>
        internal static string ScanQuantActDeact_Text {
            get {
                return ResourceManager.GetString("ScanQuantActDeact_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the target batch:.
        /// </summary>
        internal static string SelectBatch_Text {
            get {
                return ResourceManager.GetString("SelectBatch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a store.
        /// </summary>
        internal static string SelectFacility_Text {
            get {
                return ResourceManager.GetString("SelectFacility_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the intermediate product:.
        /// </summary>
        internal static string SelectIntermediate_Text {
            get {
                return ResourceManager.GetString("SelectIntermediate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or select the Bill of material:.
        /// </summary>
        internal static string SelectPartslist_Text {
            get {
                return ResourceManager.GetString("SelectPartslist_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or select the target storage:.
        /// </summary>
        internal static string SelectTargetFacility_Text {
            get {
                return ResourceManager.GetString("SelectTargetFacility_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select target facility location/bin.
        /// </summary>
        internal static string SelectTargetFacilityLocationOrBin_Text {
            get {
                return ResourceManager.GetString("SelectTargetFacilityLocationOrBin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select picking type.
        /// </summary>
        internal static string SelPickingType_Text {
            get {
                return ResourceManager.GetString("SelPickingType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available (spent, relocated,...).
        /// </summary>
        internal static string Spent_Text {
            get {
                return ResourceManager.GetString("Spent_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock correction.
        /// </summary>
        internal static string StockCorrection_Text {
            get {
                return ResourceManager.GetString("StockCorrection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction reason:.
        /// </summary>
        internal static string StockCorrectionReason_Text {
            get {
                return ResourceManager.GetString("StockCorrectionReason_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string StockQuantity_Text {
            get {
                return ResourceManager.GetString("StockQuantity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage locations.
        /// </summary>
        internal static string StorageLocations_Text {
            get {
                return ResourceManager.GetString("StorageLocations_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage location priority:.
        /// </summary>
        internal static string StorageLocationSortPriority_Text {
            get {
                return ResourceManager.GetString("StorageLocationSortPriority_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark storage locations that are relevant for sort:.
        /// </summary>
        internal static string StorageLocationsSortInfo_Text {
            get {
                return ResourceManager.GetString("StorageLocationsSortInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Blocked.
        /// </summary>
        internal static string SumBlocked_Text {
            get {
                return ResourceManager.GetString("SumBlocked_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Blocked Abs..
        /// </summary>
        internal static string SumBlockedAbsolute_Text {
            get {
                return ResourceManager.GetString("SumBlockedAbsolute_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Free.
        /// </summary>
        internal static string SumFree_Text {
            get {
                return ResourceManager.GetString("SumFree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Total.
        /// </summary>
        internal static string SumTotal_Text {
            get {
                return ResourceManager.GetString("SumTotal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timerange.
        /// </summary>
        internal static string TimeRangeFilter_Header {
            get {
                return ResourceManager.GetString("TimeRangeFilter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To storage location.
        /// </summary>
        internal static string ToStorageLocation_Text {
            get {
                return ResourceManager.GetString("ToStorageLocation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Offline-Demodata.
        /// </summary>
        internal static string UseMockDataStore_Text {
            get {
                return ResourceManager.GetString("UseMockDataStore_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username_Text {
            get {
                return ResourceManager.GetString("Username_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate and complete.
        /// </summary>
        internal static string ValidateAndComplete_Text {
            get {
                return ResourceManager.GetString("ValidateAndComplete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. View open lines.
        /// </summary>
        internal static string ViewOpenLines_Text {
            get {
                return ResourceManager.GetString("ViewOpenLines_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        internal static string WarehousePivot_Header {
            get {
                return ResourceManager.GetString("WarehousePivot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse positions.
        /// </summary>
        internal static string WarehousePositions_Text {
            get {
                return ResourceManager.GetString("WarehousePositions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace is empty..
        /// </summary>
        internal static string WorkplaceEmpty_Text {
            get {
                return ResourceManager.GetString("WorkplaceEmpty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong quant is scanned, please scan the quant with right material..
        /// </summary>
        internal static string WrongMaterial_Text {
            get {
                return ResourceManager.GetString("WrongMaterial_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong scan. Please scan a workplace..
        /// </summary>
        internal static string WrongScanWorkplace_Text {
            get {
                return ResourceManager.GetString("WrongScanWorkplace_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully position barcode on line.
        /// </summary>
        internal static string ZXingOverlay_Text {
            get {
                return ResourceManager.GetString("ZXingOverlay_Text", resourceCulture);
            }
        }
    }
}
