<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0;net10.0-android</TargetFrameworks>
    <TargetFramework Condition="'$(TargetFramework)' == ''">net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
    <ProjectReference Include="..\gip.vbm.mobile\gip.vbm.mobile\gip.vbm.mobile.csproj" />
  </ItemGroup>

</Project>
